/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pnc.document.collaboration;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        ConsoleApplication classUnderTest = new ConsoleApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
